name: perl_bioperl

description: Bioperl module - A sandbox module to run Perl one liner
keywords:
  - bioperl
tools:
  - perl:
      description: Bioperl module - A sandbox module to run Perl one liner
      homepage: https://bioperl.org
      documentation: https://bioperl.org/howtos/index.html
      tool_dev_url: https://github.com/bioperl
      doi: ""
      licence: ["perl_5"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - file:
      type: file
      description: A text file to update with a one liner

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

  - out:
      type: file
      description: The updated input file.

authors:
  - "@sguizard"
